<template>
  <div>
    <div class="flex flex-auto h-50">
      <img
        src="../../public/vertical/pexels-garon-piceli-1405422.jpeg"
        class="w-20 grow"
        alt="Photo du festival"
      /><img
        src="../../public/vertical/pexels-alena-darmel-6940242.jpeg"
        class="w-20 grow"
        alt="Photo du festival"
      /><img
        src="../../public/vertical/pexels-peter-spencer-1317374.jpeg"
        class="rounded-xl w-20 grow"
        alt="Photo du festival"
      /><img
        src="../../public/vertical/pexels-wendy-wei-1540406.jpeg"
        class="w-20 grow"
        alt="Photo du festival"
      />
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>

</style>